sudo: required
language: node_js
node_js:
  - '10'

services:
  - docker
before_script:
  - docker-compose --file docker-compose.test.yml up -d mongo
  - docker-compose --file docker-compose.test.yml up -d redis
  - docker-compose --file docker-compose.test.yml up -d app-rtc
  - docker-compose --file docker-compose.test.yml up -d app-cv
script:
  - docker-compose --file docker-compose.test.yml up app
env:
  - NODE_ENV=test
  