language: node_js


services:
  - docker

script:
  - docker-compose up --file docker-compose.test.yml
env:
  - NODE_ENV=test
cache:
  directories:
    - ./Hello/backend/node_modules
    - ./RTCVideo/node_modules
    - ./RTCVideo-previous/node_modules
    - ./CV/node_modules

  