language: node_js


services:
  - docker
before_script:
  - docker-compose up -d mongo
  - docker-compose up -d redis
  - docker-compose up -d app-rtc
  - docker-compose up -d app-cv
script:
  - docker-compose --file docker-compose.test.yml up app
env:
  - NODE_ENV=test
cache:
  directories:
    - ./Hello/backend/node_modules
    - ./RTCVideo/node_modules
    - ./RTCVideo-previous/node_modules
    - ./CV/node_modules

  