language: node_js


services:
  - docker

script:
  - docker-compose --file docker-compose.test.yml up
env:
  - NODE_ENV=test
cache:
  directories:
    - ./Hello/backend/node_modules
    - ./RTCVideo/node_modules
    - ./RTCVideo-previous/node_modules
    - ./CV/node_modules

  