language: node_js


services:
  - docker
before_script:
  - docker-compose --file docker-compose.test.yml up -d mongo
  - docker-compose --file docker-compose.test.yml up -d redis
  - docker-compose --file docker-compose.test.yml up -d app-rtc
  - docker-compose --file docker-compose.test.yml up -d app-cv
script:
  # - docker-compose --file docker-compose.test.yml up app
  - cd Hello/backend
  - sleep 3
  - npm run test:ci
env:
  - NODE_ENV=test
  