language: node_js


services:
  - docker

script:
  - docker-compose up 
  - sleep 3
  - cd ./Hello/backend/
  - npm run test 

env:
  - NODE_ENV=test
cache:
  directories:
    - ./Hello/backend/node_modules
    - ./RTCVideo/node_modules
    - ./RTCVideo-previous/node_modules
    - ./CV/node_modules

  