sudo: required
language: node_js
node_js:
  - '10'
dist: trusty
services:
  - docker
before_install:
  - npm install jest -g
  - docker-compose --file docker-compose.test.yml up -d mongo
  - docker-compose --file docker-compose.test.yml up -d redis
  - docker-compose --file docker-compose.test.yml up -d app-rtc
  - docker-compose --file docker-compose.test.yml up -d app-cv
install: 
  - cd Hello/backend && npm install
script:
  - docker-compose --file docker-compose.test.yml up app
  # - cd Hello/backend
  # - npm install 
  # - sleep 3
  # - npm run test:ci
env:
  - NODE_ENV=test
  