sudo: required
language: node_js
node_js:
  - '10'
dist: trusty
services:
  - docker
before_install:
  # - npm install jest -g
  - docker-compose --file docker-compose.test.yml up -d mongo
  - docker-compose --file docker-compose.test.yml up -d redis
  - docker-compose --file docker-compose.test.yml up -d app-rtc
  - docker-compose --file docker-compose.test.yml up -d app-cv
  - docker-compose --file docker-compose.test.yml up -d app 
script:
  - sleep 10
  - docker-compose --file docker-compose.test.yml run app  sh -c ls && cd Hello/backend && npm run test:ci
  # - cd Hello/backend
  # - npm install 
  # - npm run test:ci
env:
  - NODE_ENV=test
  