language: node_js
node_js:
  - '8'

services:
  - docker

before_install:
  - docker-compose up 

env:
  - NODE_ENV=test
cache:
  directories:
    - ./Hello/backend/node_modules
    - ./RTCVideo/node_modules
    - ./RTCVideo-previous/node_modules
    - ./CV/node_modules

script:
  - sleep 3
  - cd ./Hello/backend/
  - npm run test 