version: '3.5'
services:
  app:
    container_name: admin-pannel
    restart: always
    build: .
    volumes:
      - ./:/app
    tty: true
    ports:
      - '8085:3000'
    links:
      - "mongo:dbmongo"
      # this feature is no longer need except for aliases
    environment:
      - "NODE_ENV=docker"
      - "admin-panel_jwt=123456"
      - "adminPanel_jwt=123456"
      - "PORT=3000"
    depends_on: ["mongo"]
  mongo:
    restart: always
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27057:27017'

volumes: 
  mongo-data: