version: '3'
services:
  app:
    container_name: admin-pannel
    restart: always
    build: .
    volumes:
      - ./:/app
    tty: true
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017-27019:27017-27019'