version: '3'
services:
  app:
    container_name: admin-pannel
    restart: always
    build: .
    volumes:
      - ./:/app
    tty: true
    ports:
      - '80:3000'
    links:
      - "mongo:dbmongo"
      # this feature is no longer need except for aliases
    environment:
      - "NODE_ENV=docker"
      - "admin-panel_jwt=123456"
  mongo:
    restart: always
    image: mongo
    # ports:
    #   - '27017-27019:27017-27019'